package com.mycompany.istudy.gui;

import com.mycompany.istudy.controller.BaseController;
import com.mycompany.istudy.controller.HomeController;
import com.mycompany.istudy.db.entities.Student;
import com.mycompany.istudy.db.services.impl.StudentManager;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Cham
 */
public class ChangeAccountData extends javax.swing.JFrame {

    private final UserWin userwin;
    
    /**
     * Creates new form ChangeAccountData
     * @param userwin
     */
    public ChangeAccountData(final UserWin userwin) {
        this.userwin = userwin;
        setUndecorated(true);
        setAlwaysOnTop(true);
        initComponents();
        initElements();
    }

    private boolean validateEntries() {
        if (firstnameTextField.getText().trim().isEmpty()) {
            showErrorDialog(firstname.getText());
            return false;
        }
        if (surnameTextField.getText().trim().isEmpty()) {
            showErrorDialog(surname.getText());
            return false;
        }
        if (emailTextField.getText().trim().isEmpty()) {
            showErrorDialog(email.getText());
            return false;
        }
        if (emailReTextField.getText().trim().isEmpty()) {
            showErrorDialog(emailRe.getText());
            return false;
        }
        if (usernameTextField.getText().trim().isEmpty()) {
            showErrorDialog(username.getText());
            return false;
        }
        if (((JTextField) passwordTextField).getText().trim().isEmpty()) {
            showErrorDialog(password.getText());
            return false;
        }
        if (matNrTextField.getText().trim().isEmpty()) {
            showErrorDialog(matNr.getText());
            return false;
        }
        if (streetAndNrTextField1.getText().trim().isEmpty()) {
            showErrorDialog(address.getText());
            return false;
        }
        if (cityAndZipTextField1.getText().trim().isEmpty()) {
            showErrorDialog(cityAndZip.getText());
            return false;
        }
        if (phoneTextField1.getText().trim().isEmpty()) {
            showErrorDialog(phone.getText());
            return false;
        }
        if (dateTextField1.getText().trim().isEmpty()) {
            showErrorDialog(date.getText());
            return false;
        }

        //validate email repitition
        if (!emailTextField.getText().equals(emailReTextField.getText())) {
            JOptionPane.showMessageDialog(this,
                    "Emails are not identical",
                    "Email identical error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void showErrorDialog(String subject) {
        JOptionPane.showMessageDialog(this,
                "Please enter your " + subject,
                subject + " is empty",
                JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personalPanel = new javax.swing.JPanel();
        poersonalSubPanel = new javax.swing.JPanel();
        address = new javax.swing.JLabel();
        cityAndZip = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        accountPanel = new javax.swing.JPanel();
        accountSubPanel = new javax.swing.JPanel();
        firstname = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        surname = new javax.swing.JLabel();
        surnameTextField = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        emailRe = new javax.swing.JLabel();
        emailReTextField = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        matNrTextField = new javax.swing.JTextField();
        matNr = new javax.swing.JLabel();
        address1 = new javax.swing.JLabel();
        cityAndZip1 = new javax.swing.JLabel();
        phone1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        streetAndNrTextField1 = new javax.swing.JTextField();
        cityAndZipTextField1 = new javax.swing.JTextField();
        phoneTextField1 = new javax.swing.JTextField();
        dateTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        personalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        address.setText("Street, Nr");

        cityAndZip.setText("City, ZIP");

        phone.setText("Phone");

        date.setText("Birthday (DD-MM-YYYY)");

        javax.swing.GroupLayout poersonalSubPanelLayout = new javax.swing.GroupLayout(poersonalSubPanel);
        poersonalSubPanel.setLayout(poersonalSubPanelLayout);
        poersonalSubPanelLayout.setHorizontalGroup(
            poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(poersonalSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityAndZip, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(streetAndNrTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(cityAndZipTextField1)
                    .addComponent(phoneTextField1)
                    .addComponent(dateTextField1))
                .addContainerGap())
        );
        poersonalSubPanelLayout.setVerticalGroup(
            poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(poersonalSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address)
                    .addComponent(streetAndNrTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityAndZip)
                    .addComponent(cityAndZipTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(phoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(dateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout personalPanelLayout = new javax.swing.GroupLayout(personalPanel);
        personalPanel.setLayout(personalPanelLayout);
        personalPanelLayout.setHorizontalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(poersonalSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        personalPanelLayout.setVerticalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(poersonalSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        firstname.setText("First name");

        firstnameTextField.setBackground(new java.awt.Color(240, 240, 240));

        surname.setText("Surname");

        surnameTextField.setBackground(new java.awt.Color(240, 240, 240));

        email.setText("E-Mail");

        emailTextField.setBackground(new java.awt.Color(240, 240, 240));

        emailRe.setText("E-Mail repitition");

        emailReTextField.setBackground(new java.awt.Color(240, 240, 240));

        username.setText("Username");

        usernameTextField.setEditable(false);
        usernameTextField.setBackground(new java.awt.Color(204, 204, 204));

        password.setText("Password");

        passwordTextField.setEditable(false);
        passwordTextField.setBackground(new java.awt.Color(204, 204, 204));
        passwordTextField.setText("********");

        matNrTextField.setEditable(false);
        matNrTextField.setBackground(new java.awt.Color(204, 204, 204));

        matNr.setText("Matriculation number");

        address1.setText("Street, Nr");

        cityAndZip1.setText("City, ZIP");

        phone1.setText("Phone");

        date1.setText("Birthday");

        streetAndNrTextField1.setBackground(new java.awt.Color(240, 240, 240));

        cityAndZipTextField1.setBackground(new java.awt.Color(240, 240, 240));

        phoneTextField1.setBackground(new java.awt.Color(240, 240, 240));

        dateTextField1.setEditable(false);
        dateTextField1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout accountSubPanelLayout = new javax.swing.GroupLayout(accountSubPanel);
        accountSubPanel.setLayout(accountSubPanelLayout);
        accountSubPanelLayout.setHorizontalGroup(
            accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accountSubPanelLayout.createSequentialGroup()
                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstnameTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accountSubPanelLayout.createSequentialGroup()
                        .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(surnameTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accountSubPanelLayout.createSequentialGroup()
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accountSubPanelLayout.createSequentialGroup()
                        .addComponent(emailRe, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailReTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accountSubPanelLayout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accountSubPanelLayout.createSequentialGroup()
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accountSubPanelLayout.createSequentialGroup()
                        .addComponent(matNr, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(matNrTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accountSubPanelLayout.createSequentialGroup()
                        .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(streetAndNrTextField1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accountSubPanelLayout.createSequentialGroup()
                        .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(date1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cityAndZip1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(phone1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneTextField1)
                            .addComponent(cityAndZipTextField1)
                            .addComponent(dateTextField1))))
                .addContainerGap())
        );
        accountSubPanelLayout.setVerticalGroup(
            accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surname)
                    .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailRe)
                    .addComponent(emailReTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(matNr)
                    .addComponent(matNrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address1)
                    .addComponent(streetAndNrTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityAndZip1)
                    .addComponent(cityAndZipTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone1)
                    .addComponent(phoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date1)
                    .addComponent(dateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addComponent(accountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (validateEntries()) {
            Student student = StudentManager.getInstance().getStudent();
            student.setVorname(firstnameTextField.getText());
            student.setNachname(surnameTextField.getText());
            student.setEmailaddress(student.getEmailaddress());
            student.setStreetNr(streetAndNrTextField1.getText());
            student.setCityAndZip(cityAndZipTextField1.getText());
            student.setTelefonnummer(phoneTextField1.getText());
            StudentManager.getInstance().updateStudent(student);
            BaseController homeController = new HomeController(userwin);
            homeController.init();
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel;
    private javax.swing.JPanel accountSubPanel;
    private javax.swing.JLabel address;
    private javax.swing.JLabel address1;
    private javax.swing.JLabel cityAndZip;
    private javax.swing.JLabel cityAndZip1;
    private javax.swing.JTextField cityAndZipTextField1;
    private javax.swing.JLabel date;
    private javax.swing.JLabel date1;
    private javax.swing.JTextField dateTextField1;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emailRe;
    private javax.swing.JTextField emailReTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel matNr;
    private javax.swing.JTextField matNrTextField;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPanel personalPanel;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phone1;
    private javax.swing.JTextField phoneTextField1;
    private javax.swing.JPanel poersonalSubPanel;
    private javax.swing.JTextField streetAndNrTextField1;
    private javax.swing.JLabel surname;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

    private void initElements() {
        final Student student = StudentManager.getInstance().getStudent();
        firstnameTextField.setText(student.getVorname());
        surnameTextField.setText(student.getNachname());
        emailTextField.setText(student.getEmailaddress());
        emailReTextField.setText(student.getEmailaddress());
        usernameTextField.setText(student.getBenutzername());
        passwordTextField.setText(student.getPasswort());
        matNrTextField.setText(String.valueOf(student.getMatrikelnummer()));
        streetAndNrTextField1.setText(student.getStreetNr());
        cityAndZipTextField1.setText(student.getCityAndZip());
        phoneTextField1.setText(student.getTelefonnummer());
        final SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        dateTextField1.setText(sdf.format(student.getGeburtsdatum()));
    }
}
