/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.istudy.gui;

import com.mycompany.istudy.db.entities.Student;
import com.mycompany.istudy.db.services.impl.StudentManager;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Varuni
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        accountPanel = new javax.swing.JPanel();
        accountSubPanel = new javax.swing.JPanel();
        firstname = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        surname = new javax.swing.JLabel();
        surnameTextField = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        emailRe = new javax.swing.JLabel();
        emailReTextField = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();
        passwordRe = new javax.swing.JLabel();
        passwordReTextField = new javax.swing.JPasswordField();
        matNrTextField = new javax.swing.JTextField();
        matNr = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        personalPanel = new javax.swing.JPanel();
        poersonalSubPanel = new javax.swing.JPanel();
        address = new javax.swing.JLabel();
        streetAndNrTextField = new javax.swing.JTextField();
        cityAndZip = new javax.swing.JLabel();
        cityAndZipTextField = new javax.swing.JTextField();
        phone = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        date = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        studyPanel = new javax.swing.JPanel();
        studySubPanel = new javax.swing.JPanel();
        cityOfUniversity = new javax.swing.JLabel();
        cityOfUniversityTextField = new javax.swing.JTextField();
        nameOfUni = new javax.swing.JLabel();
        nameOfUniTextField = new javax.swing.JTextField();
        nameOfFac = new javax.swing.JLabel();
        nameOfFacTextField = new javax.swing.JTextField();
        subjectStream = new javax.swing.JLabel();
        subjectStreamTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/istudy/gui/img/registration.png"))); // NOI18N

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setText("Your account information");

        accountPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        firstname.setText("First name");

        firstnameTextField.setBackground(new java.awt.Color(240, 240, 240));

        surname.setText("Surname");

        surnameTextField.setBackground(new java.awt.Color(240, 240, 240));

        email.setText("E-Mail");

        emailTextField.setBackground(new java.awt.Color(240, 240, 240));

        emailRe.setText("E-Mail repitition");

        emailReTextField.setBackground(new java.awt.Color(240, 240, 240));

        username.setText("Username");

        usernameTextField.setBackground(new java.awt.Color(240, 240, 240));

        password.setText("Password");

        passwordTextField.setBackground(new java.awt.Color(240, 240, 240));

        passwordRe.setText("Password repitition");

        passwordReTextField.setBackground(new java.awt.Color(240, 240, 240));

        matNrTextField.setBackground(new java.awt.Color(240, 240, 240));

        matNr.setText("Matriculation number");

        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountSubPanelLayout = new javax.swing.GroupLayout(accountSubPanel);
        accountSubPanel.setLayout(accountSubPanelLayout);
        accountSubPanelLayout.setHorizontalGroup(
            accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountSubPanelLayout.createSequentialGroup()
                        .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstnameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                    .addGroup(accountSubPanelLayout.createSequentialGroup()
                        .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(surnameTextField))
                    .addGroup(accountSubPanelLayout.createSequentialGroup()
                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailTextField))
                    .addGroup(accountSubPanelLayout.createSequentialGroup()
                        .addComponent(emailRe, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailReTextField))
                    .addGroup(accountSubPanelLayout.createSequentialGroup()
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(usernameTextField))
                    .addGroup(accountSubPanelLayout.createSequentialGroup()
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordTextField))
                    .addGroup(accountSubPanelLayout.createSequentialGroup()
                        .addComponent(passwordRe, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordReTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountSubPanelLayout.createSequentialGroup()
                        .addComponent(matNr, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(matNrTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountSubPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(registerButton)))
                .addContainerGap())
        );
        accountSubPanelLayout.setVerticalGroup(
            accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(surname)
                    .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailRe)
                    .addComponent(emailReTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordRe)
                    .addComponent(passwordReTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(accountSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matNr)
                    .addComponent(matNrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout accountPanelLayout = new javax.swing.GroupLayout(accountPanel);
        accountPanel.setLayout(accountPanelLayout);
        accountPanelLayout.setHorizontalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        accountPanelLayout.setVerticalGroup(
            accountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        personalPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personal information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        address.setText("Street, Nr");

        streetAndNrTextField.setBackground(new java.awt.Color(240, 240, 240));

        cityAndZip.setText("City, ZIP");

        cityAndZipTextField.setBackground(new java.awt.Color(240, 240, 240));

        phone.setText("Phone");

        phoneTextField.setBackground(new java.awt.Color(240, 240, 240));

        date.setText("Birthday (DD-MM-YYYY)");

        dateTextField.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout poersonalSubPanelLayout = new javax.swing.GroupLayout(poersonalSubPanel);
        poersonalSubPanel.setLayout(poersonalSubPanelLayout);
        poersonalSubPanelLayout.setHorizontalGroup(
            poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(poersonalSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityAndZip, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(streetAndNrTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(cityAndZipTextField)
                    .addComponent(phoneTextField)
                    .addComponent(dateTextField))
                .addContainerGap())
        );
        poersonalSubPanelLayout.setVerticalGroup(
            poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(poersonalSubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address)
                    .addComponent(streetAndNrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityAndZip)
                    .addComponent(cityAndZipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phone)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(poersonalSubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout personalPanelLayout = new javax.swing.GroupLayout(personalPanel);
        personalPanel.setLayout(personalPanelLayout);
        personalPanelLayout.setHorizontalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(poersonalSubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        personalPanelLayout.setVerticalGroup(
            personalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personalPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(poersonalSubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        studyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Study information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        cityOfUniversity.setText("City");

        cityOfUniversityTextField.setBackground(new java.awt.Color(240, 240, 240));

        nameOfUni.setText("Name of the University");

        nameOfUniTextField.setBackground(new java.awt.Color(240, 240, 240));

        nameOfFac.setText("Name of the faculty");

        nameOfFacTextField.setBackground(new java.awt.Color(240, 240, 240));

        subjectStream.setText("Subject stream");

        subjectStreamTextField.setBackground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout studySubPanelLayout = new javax.swing.GroupLayout(studySubPanel);
        studySubPanel.setLayout(studySubPanelLayout);
        studySubPanelLayout.setHorizontalGroup(
            studySubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studySubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studySubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studySubPanelLayout.createSequentialGroup()
                        .addComponent(cityOfUniversity, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cityOfUniversityTextField))
                    .addGroup(studySubPanelLayout.createSequentialGroup()
                        .addComponent(nameOfUni, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameOfUniTextField))
                    .addGroup(studySubPanelLayout.createSequentialGroup()
                        .addComponent(nameOfFac, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameOfFacTextField))
                    .addGroup(studySubPanelLayout.createSequentialGroup()
                        .addComponent(subjectStream, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subjectStreamTextField)))
                .addContainerGap())
        );
        studySubPanelLayout.setVerticalGroup(
            studySubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studySubPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studySubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityOfUniversity)
                    .addComponent(cityOfUniversityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studySubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameOfUni)
                    .addComponent(nameOfUniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studySubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameOfFac)
                    .addComponent(nameOfFacTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studySubPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectStream)
                    .addComponent(subjectStreamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout studyPanelLayout = new javax.swing.GroupLayout(studyPanel);
        studyPanel.setLayout(studyPanelLayout);
        studyPanelLayout.setHorizontalGroup(
            studyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studySubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        studyPanelLayout.setVerticalGroup(
            studyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studyPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(studySubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo)
                        .addGap(18, 18, 18)
                        .addComponent(titleLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(titleLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(personalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(accountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        if (validateEntries()) {
            Student student = new Student();
            student.setVorname(firstnameTextField.getText());
            student.setNachname(surnameTextField.getText());
            student.setEmailaddress(emailTextField.getText());
            student.setBenutzername(usernameTextField.getText());
            student.setPasswort(((JTextField) passwordTextField).getText());
            try {
                student.setMatrikelnummer(Integer.parseInt(matNrTextField.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Matriculation number should be in number format",
                        "Number input error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            student.setStreetNr(streetAndNrTextField.getText());
            student.setCityAndZip(cityAndZipTextField.getText());
            student.setTelefonnummer(phoneTextField.getText());
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                Date date = sdf.parse(dateTextField.getText());
                student.setGeburtsdatum(date);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Date should be in this format : dd-MM-yyyy",
                        "Date input error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
            student.setCityOfUniversity(cityOfUniversityTextField.getText());
            student.setNameOfUni(nameOfUniTextField.getText());
            student.setNameOfFac(nameOfFacTextField.getText());
            student.setSubjectStream(subjectStreamTextField.getText());
            try {
                StudentManager studentManager = StudentManager.getInstance();
                studentManager.insertStudent(student);
                JOptionPane.showMessageDialog(this,
                        "Thank you for registration\nYour Account information:\n\nUser : " + student.getBenutzername() + "\n\nPlease login!",
                        "Registration information",
                        JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Registration process was not successfully. Technical error. Contact the support.",
                        "DB persistent error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private boolean validateEntries() {
        if (firstnameTextField.getText().trim().isEmpty()) {
            showErrorDialog(firstname.getText());
            return false;
        }
        if (surnameTextField.getText().trim().isEmpty()) {
            showErrorDialog(surname.getText());
            return false;
        }
        if (emailTextField.getText().trim().isEmpty()) {
            showErrorDialog(email.getText());
            return false;
        }
        if (emailReTextField.getText().trim().isEmpty()) {
            showErrorDialog(emailRe.getText());
            return false;
        }
        if (usernameTextField.getText().trim().isEmpty()) {
            showErrorDialog(username.getText());
            return false;
        }
        if (((JTextField) passwordTextField).getText().trim().isEmpty()) {
            showErrorDialog(password.getText());
            return false;
        }
        if (((JTextField) passwordReTextField).getText().trim().isEmpty()) {
            showErrorDialog(passwordRe.getText());
            return false;
        }
        if (matNrTextField.getText().trim().isEmpty()) {
            showErrorDialog(matNr.getText());
            return false;
        }
        if (streetAndNrTextField.getText().trim().isEmpty()) {
            showErrorDialog(address.getText());
            return false;
        }
        if (cityAndZipTextField.getText().trim().isEmpty()) {
            showErrorDialog(cityAndZip.getText());
            return false;
        }
        if (phoneTextField.getText().trim().isEmpty()) {
            showErrorDialog(phone.getText());
            return false;
        }
        if (dateTextField.getText().trim().isEmpty()) {
            showErrorDialog(date.getText());
            return false;
        }
        if (cityOfUniversityTextField.getText().trim().isEmpty()) {
            showErrorDialog(cityOfUniversity.getText());
            return false;
        }
        if (nameOfUniTextField.getText().trim().isEmpty()) {
            showErrorDialog(nameOfUni.getText());
            return false;
        }
        if (nameOfFacTextField.getText().trim().isEmpty()) {
            showErrorDialog(nameOfFac.getText());
            return false;
        }
        if (subjectStreamTextField.getText().trim().isEmpty()) {
            showErrorDialog(subjectStream.getText());
            return false;
        }

        //validate email repitition
        if (!emailTextField.getText().equals(emailReTextField.getText())) {
            JOptionPane.showMessageDialog(this,
                    "Emails are not identical",
                    "Email identical error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        //validate password repitition
        if (!((JTextField) passwordTextField).getText().equals(((JTextField) passwordReTextField).getText())) {
            JOptionPane.showMessageDialog(this,
                    "Passwords are not identical",
                    "Password identical error",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void showErrorDialog(String subject) {
        JOptionPane.showMessageDialog(this,
                "Please enter your " + subject,
                subject + " is empty",
                JOptionPane.ERROR_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel;
    private javax.swing.JPanel accountSubPanel;
    private javax.swing.JLabel address;
    private javax.swing.JLabel cityAndZip;
    private javax.swing.JTextField cityAndZipTextField;
    private javax.swing.JLabel cityOfUniversity;
    private javax.swing.JTextField cityOfUniversityTextField;
    private javax.swing.JLabel date;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emailRe;
    private javax.swing.JTextField emailReTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel firstname;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel matNr;
    private javax.swing.JTextField matNrTextField;
    private javax.swing.JLabel nameOfFac;
    private javax.swing.JTextField nameOfFacTextField;
    private javax.swing.JLabel nameOfUni;
    private javax.swing.JTextField nameOfUniTextField;
    private javax.swing.JLabel password;
    private javax.swing.JLabel passwordRe;
    private javax.swing.JPasswordField passwordReTextField;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPanel personalPanel;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JPanel poersonalSubPanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField streetAndNrTextField;
    private javax.swing.JPanel studyPanel;
    private javax.swing.JPanel studySubPanel;
    private javax.swing.JLabel subjectStream;
    private javax.swing.JTextField subjectStreamTextField;
    private javax.swing.JLabel surname;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables

}
