package com.mycompany.istudy.gui;

import com.mycompany.istudy.controller.pdf.PerformancePdfController;
import com.mycompany.istudy.controller.*;
import com.toedter.calendar.JDateChooser;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Varuni
 */
public class UserWin extends javax.swing.JFrame {

    private BaseController homeController;
    private BaseController subjectStreamController;
    private BaseController organiserController;
    private BaseController graphicalViewController;
    private PerformancePdfController pdfControkller;
    private BaseController calendarViewController;

    /**
     * Creates new form UserWin
     *
     * @throws java.io.IOException
     */
    public UserWin() throws IOException {
        initControllers();
        initComponents();
        initInformation();
        initFrameSettings();
    }

    private void initControllers() {
        homeController = new HomeController(this);
        subjectStreamController = new SubjectStreamController(this);
        organiserController = new OrganiserController(this);
        graphicalViewController = new GraphicalViewController(this);
        pdfControkller = new PerformancePdfController();
        calendarViewController = new CalendarViewController(this);
    }

    /**
     * prepares the gui for the user
     */
    private void initInformation() {
        List<BaseController> controllers = new ArrayList<>();
        controllers.add(homeController);
        controllers.add(subjectStreamController);
        controllers.add(organiserController);
        controllers.add(graphicalViewController);
        controllers.add(calendarViewController);

        controllers.stream().forEach((specifyController) -> {
            specifyController.init();
        });
    }

    private void initFrameSettings() {
        setMinimumSize(new Dimension(1000, 670));
        this.setResizable(Boolean.FALSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        graphicalViewjTabbedPane = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        ProfilePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        loginentriesTable = new javax.swing.JTable();
        homeusername = new javax.swing.JLabel();
        homefirstname = new javax.swing.JLabel();
        homelastname = new javax.swing.JLabel();
        homeuniversity = new javax.swing.JLabel();
        homefaculty = new javax.swing.JLabel();
        homesubject = new javax.swing.JLabel();
        homematno = new javax.swing.JLabel();
        ProfilePanel1 = new javax.swing.JPanel();
        activeSemesterJLabel = new javax.swing.JLabel();
        activeModulesJLabel = new javax.swing.JLabel();
        nextExamJLabel = new javax.swing.JLabel();
        averageJLabel = new javax.swing.JLabel();
        activeSemesterJLabelValue = new javax.swing.JLabel();
        activeModulesJLabelValue = new javax.swing.JLabel();
        nextExamJLabelValue = new javax.swing.JLabel();
        averageJLabelValue = new javax.swing.JLabel();
        savedcpJLabel = new javax.swing.JLabel();
        savedcpJLabelValue = new javax.swing.JLabel();
        cpToAchieveJLabel = new javax.swing.JLabel();
        cpToAchieveJLabelValue = new javax.swing.JLabel();
        failedExamsJLabel = new javax.swing.JLabel();
        failedExamsJLabelValue = new javax.swing.JLabel();
        passedExamsJLabel = new javax.swing.JLabel();
        passedExamsJLabelValue = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaLog = new javax.swing.JTextArea();
        SubjectStreamPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modulAndSemesterOverviewJTree = new javax.swing.JTree();
        deleteSemesterJButton = new javax.swing.JButton();
        createSemesterJButton = new javax.swing.JButton();
        controllLayeredPane = new javax.swing.JLayeredPane();
        semesterBoardPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        modulename = new javax.swing.JTextField();
        creditpoints = new javax.swing.JTextField();
        studyhours = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        createModuleButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        semesterStartDateJCalender = new com.toedter.calendar.JDateChooser();
        examinationStartDateJCalender = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        semesterLabel = new javax.swing.JLabel();
        activateDeactivateSemesterButton = new javax.swing.JButton();
        currentSemesterJLabel = new javax.swing.JLabel();
        moduleBoardPanel = new javax.swing.JPanel();
        moduleLabel = new javax.swing.JLabel();
        selectedModuleLabel = new javax.swing.JLabel();
        activateDeactivateModuleButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        modulnameModulBPanel = new javax.swing.JTextField();
        creditpointsModulBPanel = new javax.swing.JTextField();
        studyhoursModulBPanel = new javax.swing.JTextField();
        deleteModuleButton = new javax.swing.JButton();
        editModuleButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        academicRecordsJTable = new javax.swing.JTable();
        OrganiserPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        feedInfoPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        totalCalenderWeeks = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        investedHoursForAModuleJTable = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        weekJComboBox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        investedHoursJTextField = new javax.swing.JTextField();
        pushInvestedHoursButton = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        activeModuleJTable = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        CalenderPanel = new javax.swing.JPanel();
        calendarjScrollPane = new javax.swing.JScrollPane();
        calendarjTable = new javax.swing.JTable();
        nextjButton = new javax.swing.JButton();
        previousjButton = new javax.swing.JButton();
        yearjLabel = new javax.swing.JLabel();
        monthjLabel = new javax.swing.JLabel();
        calendarjComboBox = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        moduleListCalendarjComboBox = new javax.swing.JComboBox<>();
        GraphicalnViewPanel = new javax.swing.JPanel();
        ModulPerformancejPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        moduleListjComboBox = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(null);

        graphicalViewjTabbedPane.setName("Home"); // NOI18N

        ProfilePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Profile"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Firstname");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Lastname");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("University");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Faculty");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Subject stream");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Matri. no.");

        loginentriesTable.setForeground(new java.awt.Color(0, 51, 204));
        loginentriesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Time", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(loginentriesTable);

        homeusername.setForeground(new java.awt.Color(0, 51, 255));
        homeusername.setText("jLabel7");

        homefirstname.setForeground(new java.awt.Color(0, 51, 255));
        homefirstname.setText("jLabel7");

        homelastname.setForeground(new java.awt.Color(0, 51, 255));
        homelastname.setText("jLabel7");

        homeuniversity.setForeground(new java.awt.Color(0, 51, 255));
        homeuniversity.setText("jLabel7");

        homefaculty.setForeground(new java.awt.Color(0, 51, 255));
        homefaculty.setText("jLabel7");

        homesubject.setForeground(new java.awt.Color(0, 51, 255));
        homesubject.setText("jLabel7");

        homematno.setForeground(new java.awt.Color(0, 51, 255));
        homematno.setText("jLabel7");

        javax.swing.GroupLayout ProfilePanelLayout = new javax.swing.GroupLayout(ProfilePanel);
        ProfilePanel.setLayout(ProfilePanelLayout);
        ProfilePanelLayout.setHorizontalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homematno, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homeusername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homefirstname, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homelastname, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homeuniversity, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homefaculty, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                    .addGroup(ProfilePanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homesubject, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ProfilePanelLayout.setVerticalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(homeusername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(homefirstname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(homelastname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(homeuniversity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(homefaculty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(homesubject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(homematno))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        ProfilePanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Board"));

        activeSemesterJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        activeSemesterJLabel.setText("Active semester");

        activeModulesJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        activeModulesJLabel.setText("Active modules");

        nextExamJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nextExamJLabel.setText("Next exam");

        averageJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        averageJLabel.setText("Average");

        activeSemesterJLabelValue.setForeground(new java.awt.Color(0, 51, 255));
        activeSemesterJLabelValue.setText("-");

        activeModulesJLabelValue.setForeground(new java.awt.Color(0, 51, 255));
        activeModulesJLabelValue.setText("-");

        nextExamJLabelValue.setForeground(new java.awt.Color(0, 51, 255));
        nextExamJLabelValue.setText("-");

        averageJLabelValue.setForeground(new java.awt.Color(0, 51, 255));
        averageJLabelValue.setText("-");

        savedcpJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        savedcpJLabel.setText("CP (saved)");

        savedcpJLabelValue.setForeground(new java.awt.Color(0, 51, 255));
        savedcpJLabelValue.setText("-");

        cpToAchieveJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cpToAchieveJLabel.setText("CP (to achieve)");

        cpToAchieveJLabelValue.setForeground(new java.awt.Color(0, 51, 255));
        cpToAchieveJLabelValue.setText("-");

        failedExamsJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        failedExamsJLabel.setText("Failed exams");

        failedExamsJLabelValue.setForeground(new java.awt.Color(0, 51, 255));
        failedExamsJLabelValue.setText("-");

        passedExamsJLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passedExamsJLabel.setText("Passed exams");

        passedExamsJLabelValue.setForeground(new java.awt.Color(0, 51, 255));
        passedExamsJLabelValue.setText("-");

        areaLog.setEditable(false);
        areaLog.setBackground(new java.awt.Color(249, 249, 249));
        areaLog.setColumns(20);
        areaLog.setRows(5);
        jScrollPane3.setViewportView(areaLog);

        javax.swing.GroupLayout ProfilePanel1Layout = new javax.swing.GroupLayout(ProfilePanel1);
        ProfilePanel1.setLayout(ProfilePanel1Layout);
        ProfilePanel1Layout.setHorizontalGroup(
            ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(ProfilePanel1Layout.createSequentialGroup()
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(averageJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextExamJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(activeSemesterJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(activeModulesJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activeModulesJLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(activeSemesterJLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextExamJLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(averageJLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passedExamsJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(failedExamsJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(savedcpJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cpToAchieveJLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savedcpJLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpToAchieveJLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(failedExamsJLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passedExamsJLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        ProfilePanel1Layout.setVerticalGroup(
            ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfilePanel1Layout.createSequentialGroup()
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savedcpJLabel)
                            .addComponent(savedcpJLabelValue))
                        .addGap(11, 11, 11)
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpToAchieveJLabel)
                            .addComponent(cpToAchieveJLabelValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(failedExamsJLabel)
                            .addComponent(failedExamsJLabelValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(passedExamsJLabel)
                            .addComponent(passedExamsJLabelValue)))
                    .addGroup(ProfilePanel1Layout.createSequentialGroup()
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(activeSemesterJLabel)
                            .addComponent(activeSemesterJLabelValue))
                        .addGap(11, 11, 11)
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(activeModulesJLabel)
                            .addComponent(activeModulesJLabelValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextExamJLabel)
                            .addComponent(nextExamJLabelValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfilePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(averageJLabel)
                            .addComponent(averageJLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProfilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProfilePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProfilePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProfilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        graphicalViewjTabbedPane.addTab("Home", HomePanel);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        modulAndSemesterOverviewJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        modulAndSemesterOverviewJTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                modulAndSemesterOverviewJTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(modulAndSemesterOverviewJTree);

        deleteSemesterJButton.setText("DELETE SEMESTER");
        deleteSemesterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSemesterJButtonActionPerformed(evt);
            }
        });

        createSemesterJButton.setText("CREATE SEMESTER");
        createSemesterJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSemesterJButtonActionPerformed(evt);
            }
        });

        controllLayeredPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controll-Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setText("Module name");

        jLabel9.setText("Credit points");

        jLabel10.setText("Study hours");

        modulename.setBackground(new java.awt.Color(240, 240, 240));

        creditpoints.setBackground(new java.awt.Color(240, 240, 240));

        studyhours.setBackground(new java.awt.Color(240, 240, 240));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel11.setText("Expected hours to be invested for this module");

        createModuleButton.setText("CREATE MODULE");
        createModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createModuleButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Semester Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel12.setText("Start of semester");

        jLabel13.setText("Start date of Examination period ");

        semesterStartDateJCalender.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                semesterStartDateJCalenderPropertyChange(evt);
            }
        });

        examinationStartDateJCalender.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                examinationStartDateJCalenderPropertyChange(evt);
            }
        });

        jLabel14.setText("Actual Semester");

        semesterLabel.setText("0");

        activateDeactivateSemesterButton.setText("ACTIVATE");
        activateDeactivateSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateDeactivateSemesterButtonActionPerformed(evt);
            }
        });

        currentSemesterJLabel.setText("jLabel24");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentSemesterJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(examinationStartDateJCalender, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(semesterStartDateJCalender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(semesterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(activateDeactivateSemesterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(semesterLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(semesterStartDateJCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(examinationStartDateJCalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activateDeactivateSemesterButton)
                    .addComponent(currentSemesterJLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout semesterBoardPanelLayout = new javax.swing.GroupLayout(semesterBoardPanel);
        semesterBoardPanel.setLayout(semesterBoardPanelLayout);
        semesterBoardPanelLayout.setHorizontalGroup(
            semesterBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semesterBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(semesterBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, semesterBoardPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, semesterBoardPanelLayout.createSequentialGroup()
                        .addGroup(semesterBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(semesterBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creditpoints)
                            .addComponent(modulename)))
                    .addGroup(semesterBoardPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(semesterBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studyhours)
                            .addGroup(semesterBoardPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        semesterBoardPanelLayout.setVerticalGroup(
            semesterBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semesterBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(semesterBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(modulename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(semesterBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(creditpoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(semesterBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(studyhours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(createModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        moduleLabel.setText("Selected module");

        selectedModuleLabel.setText(" ");

        activateDeactivateModuleButton.setText("jButton4");
        activateDeactivateModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateDeactivateModuleButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Module name");

        jLabel18.setText("Credit points");

        jLabel19.setText("Study hours");

        modulnameModulBPanel.setBackground(new java.awt.Color(240, 240, 240));

        creditpointsModulBPanel.setBackground(new java.awt.Color(240, 240, 240));
        creditpointsModulBPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditpointsModulBPanelActionPerformed(evt);
            }
        });

        studyhoursModulBPanel.setBackground(new java.awt.Color(240, 240, 240));

        deleteModuleButton.setText("DELETE MODULE");
        deleteModuleButton.setPreferredSize(new java.awt.Dimension(121, 23));
        deleteModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteModuleButtonActionPerformed(evt);
            }
        });

        editModuleButton.setText("EDIT MODULE");
        editModuleButton.setPreferredSize(new java.awt.Dimension(121, 23));
        editModuleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editModuleButtonActionPerformed(evt);
            }
        });

        jLabel20.setText("Expected hours to be invested for this module");
        jLabel20.setPreferredSize(new java.awt.Dimension(181, 13));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Academic records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        academicRecordsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attempt", "Examination date", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        academicRecordsJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                academicRecordsJTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(academicRecordsJTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout moduleBoardPanelLayout = new javax.swing.GroupLayout(moduleBoardPanel);
        moduleBoardPanel.setLayout(moduleBoardPanelLayout);
        moduleBoardPanelLayout.setHorizontalGroup(
            moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduleBoardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(moduleBoardPanelLayout.createSequentialGroup()
                        .addComponent(moduleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectedModuleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moduleBoardPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(activateDeactivateModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(moduleBoardPanelLayout.createSequentialGroup()
                        .addGroup(moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(moduleBoardPanelLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(moduleBoardPanelLayout.createSequentialGroup()
                                        .addComponent(editModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(deleteModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(moduleBoardPanelLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(studyhoursModulBPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                                    .addComponent(modulnameModulBPanel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(creditpointsModulBPanel))))))
                .addContainerGap())
        );
        moduleBoardPanelLayout.setVerticalGroup(
            moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moduleBoardPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moduleLabel)
                    .addComponent(selectedModuleLabel))
                .addGap(18, 18, 18)
                .addComponent(activateDeactivateModuleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(modulnameModulBPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(creditpointsModulBPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studyhoursModulBPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(moduleBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteModuleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        controllLayeredPane.setLayer(semesterBoardPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        controllLayeredPane.setLayer(moduleBoardPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout controllLayeredPaneLayout = new javax.swing.GroupLayout(controllLayeredPane);
        controllLayeredPane.setLayout(controllLayeredPaneLayout);
        controllLayeredPaneLayout.setHorizontalGroup(
            controllLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(semesterBoardPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(controllLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(moduleBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controllLayeredPaneLayout.setVerticalGroup(
            controllLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(semesterBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(controllLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(moduleBoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SubjectStreamPanelLayout = new javax.swing.GroupLayout(SubjectStreamPanel);
        SubjectStreamPanel.setLayout(SubjectStreamPanelLayout);
        SubjectStreamPanelLayout.setHorizontalGroup(
            SubjectStreamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectStreamPanelLayout.createSequentialGroup()
                .addGroup(SubjectStreamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SubjectStreamPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(deleteSemesterJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createSemesterJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controllLayeredPane))
        );
        SubjectStreamPanelLayout.setVerticalGroup(
            SubjectStreamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubjectStreamPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SubjectStreamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteSemesterJButton)
                    .addComponent(createSemesterJButton))
                .addGap(6, 6, 6))
            .addComponent(controllLayeredPane)
        );

        graphicalViewjTabbedPane.addTab("Subject stream", SubjectStreamPanel);

        jLabel16.setText("Total calender weeks");

        totalCalenderWeeks.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Invested hours per week for a module", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        investedHoursForAModuleJTable.setAutoCreateRowSorter(true);
        investedHoursForAModuleJTable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        investedHoursForAModuleJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Week", "Invested hours"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(investedHoursForAModuleJTable);

        jLabel17.setText("Week");

        weekJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel21.setText("=>");

        pushInvestedHoursButton.setText("SUBMIT");
        pushInvestedHoursButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pushInvestedHoursButtonActionPerformed(evt);
            }
        });

        jLabel22.setText("hour(s)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(weekJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel21)
                        .addGap(32, 32, 32)
                        .addComponent(investedHoursJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addGap(52, 52, 52)
                        .addComponent(pushInvestedHoursButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(weekJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(investedHoursJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pushInvestedHoursButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Active modules", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        activeModuleJTable.setAutoCreateRowSorter(true);
        activeModuleJTable.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        activeModuleJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Semester", "Activated modules", "Expected study hours per week per module  ", "ECTS points", "Study hours"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        activeModuleJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activeModuleJTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(activeModuleJTable);
        if (activeModuleJTable.getColumnModel().getColumnCount() > 0) {
            activeModuleJTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel23.setText("Need an active semester and the dates to be calculated");

        javax.swing.GroupLayout feedInfoPanelLayout = new javax.swing.GroupLayout(feedInfoPanel);
        feedInfoPanel.setLayout(feedInfoPanelLayout);
        feedInfoPanelLayout.setHorizontalGroup(
            feedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(feedInfoPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalCalenderWeeks, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(feedInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(feedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        feedInfoPanelLayout.setVerticalGroup(
            feedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feedInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(feedInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(totalCalenderWeeks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Feed me some Infos!", feedInfoPanel);

        javax.swing.GroupLayout OrganiserPanelLayout = new javax.swing.GroupLayout(OrganiserPanel);
        OrganiserPanel.setLayout(OrganiserPanelLayout);
        OrganiserPanelLayout.setHorizontalGroup(
            OrganiserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        OrganiserPanelLayout.setVerticalGroup(
            OrganiserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        graphicalViewjTabbedPane.addTab("Organiser", OrganiserPanel);

        CalenderPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        calendarjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        calendarjTable.setRowSelectionAllowed(false);
        calendarjScrollPane.setViewportView(calendarjTable);

        nextjButton.setText("Next");
        nextjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextjButtonActionPerformed(evt);
            }
        });

        previousjButton.setText("Previous");
        previousjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousjButtonActionPerformed(evt);
            }
        });

        yearjLabel.setText("Select year:");

        calendarjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        calendarjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarjComboBoxActionPerformed(evt);
            }
        });

        jLabel26.setText("Please select the Module");

        moduleListCalendarjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleListCalendarjComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CalenderPanelLayout = new javax.swing.GroupLayout(CalenderPanel);
        CalenderPanel.setLayout(CalenderPanelLayout);
        CalenderPanelLayout.setHorizontalGroup(
            CalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalenderPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(CalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalenderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(74, 74, 74)
                        .addComponent(moduleListCalendarjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(CalenderPanelLayout.createSequentialGroup()
                            .addComponent(yearjLabel)
                            .addGap(29, 29, 29)
                            .addComponent(calendarjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(CalenderPanelLayout.createSequentialGroup()
                            .addComponent(previousjButton)
                            .addGap(292, 292, 292)
                            .addComponent(monthjLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nextjButton))
                        .addComponent(calendarjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        CalenderPanelLayout.setVerticalGroup(
            CalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CalenderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(moduleListCalendarjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthjLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(previousjButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nextjButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendarjScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendarjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearjLabel))
                .addGap(50, 50, 50))
        );

        graphicalViewjTabbedPane.addTab("Calender", CalenderPanel);

        ModulPerformancejPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mthematik 1"));
        ModulPerformancejPanel.setLayout(new java.awt.BorderLayout());

        jLabel24.setText("Weekly Performance");

        moduleListjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleListjComboBoxActionPerformed(evt);
            }
        });

        jLabel25.setText("Please select the Module");

        javax.swing.GroupLayout GraphicalnViewPanelLayout = new javax.swing.GroupLayout(GraphicalnViewPanel);
        GraphicalnViewPanel.setLayout(GraphicalnViewPanelLayout);
        GraphicalnViewPanelLayout.setHorizontalGroup(
            GraphicalnViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphicalnViewPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(GraphicalnViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GraphicalnViewPanelLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(74, 74, 74)
                        .addComponent(moduleListjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel24)
                    .addComponent(ModulPerformancejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(684, Short.MAX_VALUE))
        );
        GraphicalnViewPanelLayout.setVerticalGroup(
            GraphicalnViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GraphicalnViewPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel24)
                .addGap(22, 22, 22)
                .addGroup(GraphicalnViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(moduleListjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(ModulPerformancejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );

        graphicalViewjTabbedPane.addTab("Graphical view", GraphicalnViewPanel);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Functions");

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Show me my performance");
        deleteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphicalViewjTabbedPane)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(graphicalViewjTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void moduleListjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleListjComboBoxActionPerformed
        ((GraphicalViewController) graphicalViewController).createGraph();
    }//GEN-LAST:event_moduleListjComboBoxActionPerformed

    private void activeModuleJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activeModuleJTableMouseClicked
        ((OrganiserController) organiserController).prepareTableToBookInvestedHours();
    }//GEN-LAST:event_activeModuleJTableMouseClicked

    private void pushInvestedHoursButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pushInvestedHoursButtonActionPerformed
        ((OrganiserController) organiserController).pushHours();
    }//GEN-LAST:event_pushInvestedHoursButtonActionPerformed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked

    }//GEN-LAST:event_jPanel4MouseClicked

    private void academicRecordsJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_academicRecordsJTableMouseClicked
        //create
        if (SwingUtilities.isLeftMouseButton(evt)) {
            if (evt.getClickCount() == 2) {
                ((SubjectStreamController) subjectStreamController).createTryRow();
            }
        } //remove
        else if (SwingUtilities.isRightMouseButton(evt)) {
            if (evt.getClickCount() == 2) {
                ((SubjectStreamController) subjectStreamController).removeTryRow();
            }
        } //edit
        else if (SwingUtilities.isMiddleMouseButton(evt)) {
            ((SubjectStreamController) subjectStreamController).realizeTryDetailEntering();
        }
    }//GEN-LAST:event_academicRecordsJTableMouseClicked

    private void editModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editModuleButtonActionPerformed
        ((SubjectStreamController) subjectStreamController).editModule();
    }//GEN-LAST:event_editModuleButtonActionPerformed

    private void deleteModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteModuleButtonActionPerformed
        ((SubjectStreamController) subjectStreamController).deleteModule();
    }//GEN-LAST:event_deleteModuleButtonActionPerformed

    private void creditpointsModulBPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditpointsModulBPanelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditpointsModulBPanelActionPerformed

    private void activateDeactivateModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateDeactivateModuleButtonActionPerformed
        ((SubjectStreamController) subjectStreamController).activateDeactivateModule();
    }//GEN-LAST:event_activateDeactivateModuleButtonActionPerformed

    private void activateDeactivateSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateDeactivateSemesterButtonActionPerformed
        ((SubjectStreamController) subjectStreamController).activateDeactivateSemester();
    }//GEN-LAST:event_activateDeactivateSemesterButtonActionPerformed

    private void examinationStartDateJCalenderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_examinationStartDateJCalenderPropertyChange
        ((SubjectStreamController) subjectStreamController).setExaminationStartDate();
    }//GEN-LAST:event_examinationStartDateJCalenderPropertyChange

    private void semesterStartDateJCalenderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_semesterStartDateJCalenderPropertyChange
        ((SubjectStreamController) subjectStreamController).setSemesterStartDate();
    }//GEN-LAST:event_semesterStartDateJCalenderPropertyChange

    private void createModuleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createModuleButtonActionPerformed
        ((SubjectStreamController) subjectStreamController).createModul();
    }//GEN-LAST:event_createModuleButtonActionPerformed

    private void createSemesterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSemesterJButtonActionPerformed
        ((SubjectStreamController) subjectStreamController).createSemester();
    }//GEN-LAST:event_createSemesterJButtonActionPerformed

    private void deleteSemesterJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSemesterJButtonActionPerformed
        ((SubjectStreamController) subjectStreamController).deleteSemester();
    }//GEN-LAST:event_deleteSemesterJButtonActionPerformed

    private void modulAndSemesterOverviewJTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_modulAndSemesterOverviewJTreeValueChanged
        ((SubjectStreamController) subjectStreamController).setModuleAndSemestertrOverviewJtree(evt.getPath());
    }//GEN-LAST:event_modulAndSemesterOverviewJTreeValueChanged

    private void deleteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMenuItemActionPerformed
        JFileChooser jfc = new JFileChooser(new File("."));
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValue = jfc.showOpenDialog(this);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            pdfControkller.generatePDF(selectedFile.getAbsolutePath(), this);
        } 
    }//GEN-LAST:event_deleteMenuItemActionPerformed

    private void previousjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousjButtonActionPerformed
        ((CalendarViewController) calendarViewController).previousMonth();
    }//GEN-LAST:event_previousjButtonActionPerformed

    private void nextjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextjButtonActionPerformed
        ((CalendarViewController) calendarViewController).nextMonth();
    }//GEN-LAST:event_nextjButtonActionPerformed

    private void calendarjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarjComboBoxActionPerformed
        ((CalendarViewController) calendarViewController).changeYear();
    }//GEN-LAST:event_calendarjComboBoxActionPerformed

    private void moduleListCalendarjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleListCalendarjComboBoxActionPerformed
        ((CalendarViewController) calendarViewController).showInvestedHoursForModule();
    }//GEN-LAST:event_moduleListCalendarjComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CalenderPanel;
    private javax.swing.JPanel GraphicalnViewPanel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel ModulPerformancejPanel;
    private javax.swing.JPanel OrganiserPanel;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JPanel ProfilePanel1;
    private javax.swing.JPanel SubjectStreamPanel;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JTable academicRecordsJTable;
    private javax.swing.JButton activateDeactivateModuleButton;
    private javax.swing.JButton activateDeactivateSemesterButton;
    private javax.swing.JTable activeModuleJTable;
    private javax.swing.JLabel activeModulesJLabel;
    private javax.swing.JLabel activeModulesJLabelValue;
    private javax.swing.JLabel activeSemesterJLabel;
    private javax.swing.JLabel activeSemesterJLabelValue;
    private javax.swing.JTextArea areaLog;
    private javax.swing.JLabel averageJLabel;
    private javax.swing.JLabel averageJLabelValue;
    private javax.swing.JComboBox<String> calendarjComboBox;
    private javax.swing.JScrollPane calendarjScrollPane;
    private javax.swing.JTable calendarjTable;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JLayeredPane controllLayeredPane;
    private javax.swing.JLabel cpToAchieveJLabel;
    private javax.swing.JLabel cpToAchieveJLabelValue;
    private javax.swing.JButton createModuleButton;
    private javax.swing.JButton createSemesterJButton;
    private javax.swing.JTextField creditpoints;
    private javax.swing.JTextField creditpointsModulBPanel;
    private javax.swing.JLabel currentSemesterJLabel;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JButton deleteModuleButton;
    private javax.swing.JButton deleteSemesterJButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JButton editModuleButton;
    private com.toedter.calendar.JDateChooser examinationStartDateJCalender;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JLabel failedExamsJLabel;
    private javax.swing.JLabel failedExamsJLabelValue;
    private javax.swing.JPanel feedInfoPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTabbedPane graphicalViewjTabbedPane;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel homefaculty;
    private javax.swing.JLabel homefirstname;
    private javax.swing.JLabel homelastname;
    private javax.swing.JLabel homematno;
    private javax.swing.JLabel homesubject;
    private javax.swing.JLabel homeuniversity;
    private javax.swing.JLabel homeusername;
    private javax.swing.JTable investedHoursForAModuleJTable;
    private javax.swing.JTextField investedHoursJTextField;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable loginentriesTable;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTree modulAndSemesterOverviewJTree;
    private javax.swing.JPanel moduleBoardPanel;
    private javax.swing.JLabel moduleLabel;
    private javax.swing.JComboBox<String> moduleListCalendarjComboBox;
    private javax.swing.JComboBox<String> moduleListjComboBox;
    private javax.swing.JTextField modulename;
    private javax.swing.JTextField modulnameModulBPanel;
    private javax.swing.JLabel monthjLabel;
    private javax.swing.JLabel nextExamJLabel;
    private javax.swing.JLabel nextExamJLabelValue;
    private javax.swing.JButton nextjButton;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JLabel passedExamsJLabel;
    private javax.swing.JLabel passedExamsJLabelValue;
    private javax.swing.JButton previousjButton;
    private javax.swing.JButton pushInvestedHoursButton;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel savedcpJLabel;
    private javax.swing.JLabel savedcpJLabelValue;
    private javax.swing.JLabel selectedModuleLabel;
    private javax.swing.JPanel semesterBoardPanel;
    private javax.swing.JLabel semesterLabel;
    private com.toedter.calendar.JDateChooser semesterStartDateJCalender;
    private javax.swing.JTextField studyhours;
    private javax.swing.JTextField studyhoursModulBPanel;
    private javax.swing.JTextField totalCalenderWeeks;
    private javax.swing.JComboBox<String> weekJComboBox;
    private javax.swing.JLabel yearjLabel;
    // End of variables declaration//GEN-END:variables

    //Getter
    public JLabel getHomefaculty() {
        return homefaculty;
    }

    public JLabel getHomefirstname() {
        return homefirstname;
    }

    public JLabel getHomelastname() {
        return homelastname;
    }

    public JLabel getHomematno() {
        return homematno;
    }

    public JLabel getHomesubject() {
        return homesubject;
    }

    public JLabel getHomeuniversity() {
        return homeuniversity;
    }

    public JLabel getHomeusername() {
        return homeusername;
    }

    public JTable getLoginentriesTable() {
        return loginentriesTable;
    }

    public JPanel getModuleBoardPanel() {
        return moduleBoardPanel;
    }

    public JPanel getSemesterBoardPanel() {
        return semesterBoardPanel;
    }

    public JTree getModulAndSemesterOverviewJTree() {
        return modulAndSemesterOverviewJTree;
    }

    public JTextField getModulename() {
        return modulename;
    }

    public JTextField getCreditpoints() {
        return creditpoints;
    }

    public JTextField getStudyhours() {
        return studyhours;
    }

    public JLabel getSemesterLabel() {
        return semesterLabel;
    }

    public JDateChooser getSemesterStartDateJCalender() {
        return semesterStartDateJCalender;
    }

    public JDateChooser getExaminationStartDateJCalender() {
        return examinationStartDateJCalender;
    }

    public JButton getActivateDeactivateSemesterButton() {
        return activateDeactivateSemesterButton;
    }

    public JLabel getCurrentSemesterJLabel() {
        return currentSemesterJLabel;
    }

    public JButton getActivateDeactivateModuleButton() {
        return activateDeactivateModuleButton;
    }

    public JLabel getSelectedModuleLabel() {
        return selectedModuleLabel;
    }

    public JTextField getCreditpointsModulBPanel() {
        return creditpointsModulBPanel;
    }

    public JTextField getModulnameModulBPanel() {
        return modulnameModulBPanel;
    }

    public JTextField getStudyhoursModulBPanel() {
        return studyhoursModulBPanel;
    }

    public JComboBox<String> getWeekJComboBox() {
        return weekJComboBox;
    }

    public JTable getActiveModuleJTable() {
        return activeModuleJTable;
    }

    public JTextField getTotalCalenderWeeks() {
        return totalCalenderWeeks;
    }

    public JTable getInvestedHoursForAModuleJTable() {
        return investedHoursForAModuleJTable;
    }

    public JTextField getInvestedHoursJTextField() {
        return investedHoursJTextField;
    }

    public JComboBox<String> getModuleListjComboBox() {
        return moduleListjComboBox;
    }
    
    public JComboBox<String> getModuleListCalendarjComboBox() {
        return moduleListCalendarjComboBox;
    }

    public JPanel getModulPerformancejPanel() {
        return ModulPerformancejPanel;
    }

    public JTable getAcademicRecordsJTable() {
        return academicRecordsJTable;
    }

    public JTable getcalendarjTable() {
        return calendarjTable;
    }

    public JComboBox getCalendarjComboBox() {
        return calendarjComboBox;
    }

    public JScrollPane getCalendarjScrollPane(DefaultTableModel modelCalendarTable) {
        return calendarjScrollPane;
    }

    public JButton getPreviousjButton() {
        return previousjButton;
    }

    public JButton getNextjButton() {
        return nextjButton;
    }

    public JLabel getYearjLabel() {
        return yearjLabel;
    }

    public JLabel getMonthjLabel() {
        return monthjLabel;
    }

    public JLabel getActiveModulesJLabel() {
        return activeModulesJLabel;
    }

    public void setActiveModulesJLabel(JLabel activeModulesJLabel) {
        this.activeModulesJLabel = activeModulesJLabel;
    }

    public JLabel getActiveModulesJLabelValue() {
        return activeModulesJLabelValue;
    }

    public void setActiveModulesJLabelValue(JLabel activeModulesJLabelValue) {
        this.activeModulesJLabelValue = activeModulesJLabelValue;
    }

    public JLabel getActiveSemesterJLabel() {
        return activeSemesterJLabel;
    }

    public void setActiveSemesterJLabel(JLabel activeSemesterJLabel) {
        this.activeSemesterJLabel = activeSemesterJLabel;
    }

    public JLabel getActiveSemesterJLabelValue() {
        return activeSemesterJLabelValue;
    }

    public void setActiveSemesterJLabelValue(JLabel activeSemesterJLabelValue) {
        this.activeSemesterJLabelValue = activeSemesterJLabelValue;
    }

    public JLabel getAverageJLabel() {
        return averageJLabel;
    }

    public void setAverageJLabel(JLabel averageJLabel) {
        this.averageJLabel = averageJLabel;
    }

    public JLabel getAverageJLabelValue() {
        return averageJLabelValue;
    }

    public void setAverageJLabelValue(JLabel averageJLabelValue) {
        this.averageJLabelValue = averageJLabelValue;
    }

    public JLabel getCpToAchieveJLabel() {
        return cpToAchieveJLabel;
    }

    public void setCpToAchieveJLabel(JLabel cpToAchieveJLabel) {
        this.cpToAchieveJLabel = cpToAchieveJLabel;
    }

    public JLabel getCpToAchieveJLabelValue() {
        return cpToAchieveJLabelValue;
    }

    public void setCpToAchieveJLabelValue(JLabel cpToAchieveJLabelValue) {
        this.cpToAchieveJLabelValue = cpToAchieveJLabelValue;
    }

    public JLabel getFailedExamsJLabel() {
        return failedExamsJLabel;
    }

    public void setFailedExamsJLabel(JLabel failedExamsJLabel) {
        this.failedExamsJLabel = failedExamsJLabel;
    }

    public JLabel getFailedExamsJLabelValue() {
        return failedExamsJLabelValue;
    }

    public void setFailedExamsJLabelValue(JLabel failedExamsJLabelValue) {
        this.failedExamsJLabelValue = failedExamsJLabelValue;
    }

    public JLabel getNextExamJLabel() {
        return nextExamJLabel;
    }

    public void setNextExamJLabel(JLabel nextExamJLabel) {
        this.nextExamJLabel = nextExamJLabel;
    }

    public JLabel getNextExamJLabelValue() {
        return nextExamJLabelValue;
    }

    public void setNextExamJLabelValue(JLabel nextExamJLabelValue) {
        this.nextExamJLabelValue = nextExamJLabelValue;
    }

    public JLabel getPassedExamsJLabel() {
        return passedExamsJLabel;
    }

    public void setPassedExamsJLabel(JLabel passedExamsJLabel) {
        this.passedExamsJLabel = passedExamsJLabel;
    }

    public JLabel getPassedExamsJLabelValue() {
        return passedExamsJLabelValue;
    }

    public void setPassedExamsJLabelValue(JLabel passedExamsJLabelValue) {
        this.passedExamsJLabelValue = passedExamsJLabelValue;
    }

    public JLabel getSavedcpJLabel() {
        return savedcpJLabel;
    }

    public void setSavedcpJLabel(JLabel savedcpJLabel) {
        this.savedcpJLabel = savedcpJLabel;
    }

    public JLabel getSavedcpJLabelValue() {
        return savedcpJLabelValue;
    }

    public void setSavedcpJLabelValue(JLabel savedcpJLabelValue) {
        this.savedcpJLabelValue = savedcpJLabelValue;
    }
    
    

}
